.github/workflows/move_tests.yaml
SECURITY.md
core/Move.toml
core/sources/domain_e2e_tests.move
core/sources/domains.move
core/sources/test_helper.move
sh_scripts/dev_setup.sh
sh_scripts/move_tests.sh

This is just a merge of `main` into `testnet`

Adds primary names feature to testnet

---

core/sources/domains.move

Option<String> is no longer a valid entry fun argument type.

Fixes compilation issue with legacy entry fun

---

core/sources/domain_e2e_tests.move
core/sources/domains.move

`set_name_address` etc will now fail for expired names

Return false in ownership check if expired

---

.github/workflows/move_tests.yaml
.gitignore
SECURITY.md
core/Move.toml
core/sources/config.move
core/sources/domain_e2e_tests.move
core/sources/domains.move
core/sources/subdomain_e2e_tests.move
core/sources/test_helper.move
core/sources/token_helper.move
init_reverse_lookup_registry_v1/Move.toml
init_reverse_lookup_registry_v1/sources/script.move
sh_scripts/dev_setup.sh
sh_scripts/move_tests.sh

Merge testnet into mainnet so that mainnet has the latest changes for Primary Name.

[Primary Name] merge testnet branch into mainnet branch 

---

core/sources/domains.move
init_reverse_lookup_registry_v1/Move.toml
init_reverse_lookup_registry_v1/sources/script.move

only verified via local testing, but I'll fall back to the script if something goes wrong during deploy...

swap init_reverse_lookup_registry_v1 to entry

---

core_v2/sources/domains.move

[not used] add new struct for manager, domain, subdomain

---

core_v2/sources/domains.move

Next step: make subdomain its own collection, in this PR domain and subdomain still live in 1 collection.

Use new struct to mint token

---

core_v2/Move.toml
core_v2/sources/domains.move

In this PR I add a renewal event and address some comments from the previous PR
- change the function name from `validate_domain_name_string()` to `validate_name_string()`
- change the error code in line 600

[ans] adding renewal events 

---

core_v2/sources/domain_e2e_tests.move
core_v2/sources/domains.move
core_v2/sources/readme.md
core_v2/sources/subdomain_e2e_tests.move
core_v2/sources/test_helper.move

NOTE: i did not rename it in v1 code.

rename name address to target address to avoid confusion

---

core_v2/sources/domains.move

remove the suffix because I don't know what they mean

[ans] remove the suffix V1 and V2

---

core_v2/sources/domains.move
core_v2/sources/subdomain_e2e_tests.move

combine domain and subdomain errors

[ans] remove unused errors

---

core_v2/sources/domain_e2e_tests.move
core_v2/sources/domains.move
core_v2/sources/subdomain_e2e_tests.move

adding the force_renew_domain function
move the paying price part out of renew_domain_internal
`aptos move test`

[ans] adding force_set_name_expiration function

---

core_v2/sources/domains.move
router/sources/domain_admin_tests.move
router/sources/migration_tests.move
router/sources/primary_name_tests.move
router/sources/registration_tests.move
router/sources/router.move
router/sources/subdomain_transfer_tests.move

1. add a new param to register_subdomain for domain admin to decide whether subdomain owner can transfer subdomain
2. add new entry function to enable subdomain owner to transfer subdomain
3. add new entry function to disable subdomain owner to transfer subdomain

domain owner can disable and enable subdomain transfer

---

core_v2/sources/domain_e2e_tests.move
core_v2/sources/domains.move
core_v2/sources/query_helper.move
core_v2/sources/subdomain_e2e_tests.move
core_v2/sources/test_helper.move
router/sources/router.move

unify the function naming as verb first like name_is_registered to is_name_registered

[ans] rename functions

---

core_v2/sources/domain_e2e_tests.move
router/sources/router.move

[ans] use test_ as prefix for all tests

---

core_v2/sources/domain_e2e_tests.move
core_v2/sources/domains.move
core_v2/sources/subdomain_e2e_tests.move
core_v2/sources/test_helper.move
router/sources/router.move

switch the order of the domain/subdomain input so that domain is first.

[ans] switch domain subdomain input order

---

core_v2/sources/domain_e2e_tests.move
core_v2/sources/domains.move
core_v2/sources/subdomain_e2e_tests.move
core_v2/sources/test_helper.move
router/sources/router.move

- rename
- change order of domain/subdomain

[ans] rename name_is_registerable

---

core_v2/sources/domains.move

remove `register_domain_generic`

[ans] remove unused layer of function

---

core_v2/sources/domains.move

I didn't change any code but just moving them around for better readability

[ans] moving code order around

---

router/sources/router.move

I haven't removed the set primary name  in domains.move. (so that I don't break any test :P) 
will remove the that part if this works.

[ans] set primary name in router

---

core_v2/sources/v2_config.move
core_v2/sources/v2_domain_e2e_tests.move
core_v2/sources/v2_domains.move

copy https://github.com/aptos-labs/aptos-names-contracts/pull/89 and do it in v2

support reregistration grace sec v2

---

core_v2/sources/v2_domains.move

we do not support burn v2 name now

clean up burner signer in v2

---

README.md
bulk_migrate/Move.toml
bulk_migrate/README.md
bulk_migrate/sources/migrate.move
bulk_migrate/sources/migrate_tests.move
router/sources/migration_tests.move
router/sources/router.move
sh_scripts/move_publish.sh
sh_scripts/move_tests.sh

Note: names must be passed in in the correct order (e.g. domain_names: [d1, d1], subdomain_names: [none, s1]), otherwise tx will fail (and no name will be migrated)
also add a publish script for testing

add new contract for bulk migrate 

---

core_v2/sources/v2_domains.move
core_v2/sources/v2_subdomain_e2e_tests.move

[ans] return derived expiration date for get_props

---

.gitignore
core/Move.toml
core/sources/config.move
core/sources/domain_e2e_tests.move
core/sources/domains.move
core/sources/is_enabled_tests.move
core/sources/subdomain_e2e_tests.move
core/sources/test_helper.move
sh_scripts/move_tests.sh

This reverts commit b3bd3c0909473902cba56afbcd4c142ad255f2d5, reversing changes made to 995171ce11488e2f2faff3ba85b17d76f2b7d8cb.
Restore the v1 update

Revert "Merge pull request #124 from aptos-labs/j/revert-v1-update"

---

router/sources/migration_tests.move
router/sources/router.move

add 2 new error type for name already migrated and cannot migrate subdomain before migrate domain

make migration error clear

---

core_v2/sources/v2_domain_e2e_tests.move
core_v2/sources/v2_domains.move
core_v2/sources/v2_subdomain_e2e_tests.move
core_v2/sources/v2_test_helper.move
router/sources/primary_name_tests.move
router/sources/renewal_domain_tests.move
router/sources/router.move
router/sources/target_address_tests.move

[ans] add expiry check when get target address and primary name

---

core_v2/sources/v2_domain_e2e_tests.move
core_v2/sources/v2_domains.move
core_v2/sources/v2_subdomain_e2e_tests.move
core_v2/sources/v2_test_helper.move
router/sources/router.move
router/sources/tests/renewal_domain_tests.move
router/sources/tests/target_address_tests.move

split the function into `get_target_address_from_name` and `get_expiration_sec_from_name`

[ans] split get_name_props

---

core/sources/config.move
core/sources/domain_e2e_tests.move
core/sources/domains.move
core/sources/is_enabled_tests.move
core/sources/subdomain_e2e_tests.move
core/sources/test_helper.move

will merge to main so that https://github.com/aptos-labs/aptos-names-contracts/pull/23 won't include those changes

[ans] v1 change

---

core_v2/sources/v2_config.move
core_v2/sources/v2_domains.move
sh_scripts/move_tests.sh

`max_number_of_years_registered` -> `max_number_of_seconds_registered`

use max seconds instead of years

---

bulk_migrate/Move.toml
bulk_migrate/README.md
bulk_migrate/sources/script.move

this is the follow up of #176 
we want to migrate a series of reserved names from v1 to v2, then extend their expiration to forever.
run this script to migrate names from v2 to v1 on behalf of the owner
run the script from #176  to extend the expiration on behalf of admin

[ans] bulk migrate script
